apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments-api.fullname" . }}
  labels:
    app: {{ include "payments-api.name" . }}
    chart: {{ include "payments-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "payments-api.fullname" . }}
