apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharp-backend
  template:
    metadata:
      labels:
        app: csharp-backend
    spec:
      containers:
        - name: csharp-backend
          image: csharp-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-backend
spec:
  selector:
    app: csharp-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort